#!/usr/bin/env bash
# =============================================================================
# PegSentinel — Full Local Devnet Test
# Fully automated: deploys everything, stress tests, verifies buffer cycle.
#
# Usage:
#   chmod +x test_local.sh
#   ./test_local.sh
#
# Run from v4_hook project root. Requires anvil + forge + cast in PATH.
# =============================================================================

set -uo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC}   $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
die()     { echo -e "${RED}[ERR]${NC}  $*"; exit 1; }

section() {
  echo ""
  echo -e "${YELLOW}══════════════════════════════════════${NC}"
  echo -e "${YELLOW}  $*${NC}"
  echo -e "${YELLOW}══════════════════════════════════════${NC}"
}

# ── Config ────────────────────────────────────────────────────────────────────
RPC="http://127.0.0.1:8545"
CHAIN_ID=421614
ANVIL_PK="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
ANVIL_ADDR="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
FORGE="forge script --rpc-url $RPC --broadcast --via-ir -vv --non-interactive"
CAST_SEND="cast send --rpc-url $RPC --confirmations 1"

# Amounts (6 decimals)
AMT_CONCENTRATED=10000000000   # 10,000
AMT_VAULT_FUND=50000000000     # 50,000
AMT_BACKSTOP=1000000000000     # 1,000,000
AMT_SWAP_STRESS=30000000000    # 30,000 — lands ~tick -197
AMT_SWAP_RECOVERY=80000000000  # 80,000 — enough to recover past -30

ENV_OUT=".env.anvil.generated"
ANVIL_PID_FILE="/tmp/anvil_pegsentinel.pid"

# ── Helper: read contractAddress from broadcast JSON ─────────────────────────
broadcast_addr() {
  local script="$1" idx="${2:-0}"
  local file="broadcast/${script}/${CHAIN_ID}/run-latest.json"
  [[ -f "$file" ]] || die "Broadcast not found: $file"
  python3 -c "
import json
d = json.load(open('$file'))
addrs = [tx['contractAddress'] for tx in d.get('transactions', [])
         if tx.get('transactionType') in ('CREATE', 'CREATE2') and tx.get('contractAddress')]
print(addrs[$idx] if len(addrs) > $idx else '')
" 2>/dev/null
}

# ── Helper: upsert key in ENV_OUT and export ──────────────────────────────────
setenv() {
  local key="$1" val="$2"
  if [[ -f "$ENV_OUT" ]] && grep -q "^${key}=" "$ENV_OUT" 2>/dev/null; then
    sed -i "s|^${key}=.*|${key}=${val}|" "$ENV_OUT"
  else
    echo "${key}=${val}" >> "$ENV_OUT"
  fi
  export "$key"="$val"
}

# ── Cleanup ───────────────────────────────────────────────────────────────────
cleanup() {
  if [[ -f "$ANVIL_PID_FILE" ]]; then
    local pid; pid=$(cat "$ANVIL_PID_FILE")
    kill "$pid" 2>/dev/null && info "Anvil stopped (pid $pid)" || true
    rm -f "$ANVIL_PID_FILE"
  fi
}
trap cleanup EXIT

# ── Load .env ─────────────────────────────────────────────────────────────────
[[ -f .env ]] && { set -a; source .env; set +a; }

DEPLOY_PK="${PRIVATE_KEY:-$ANVIL_PK}"
DEPLOY_ADDR=$(cast wallet address --private-key "$DEPLOY_PK" 2>/dev/null || echo "$ANVIL_ADDR")

# Init env output
echo "# Auto-generated by test_local.sh — $(date)" > "$ENV_OUT"
setenv "PRIVATE_KEY"    "$DEPLOY_PK"
setenv "WALLET_ADDRESS" "$DEPLOY_ADDR"

# =============================================================================
section "STEP 0 — Start Anvil"
# =============================================================================

pkill -f "anvil.*8545" 2>/dev/null || true
sleep 1

info "Starting anvil (chain $CHAIN_ID)..."
# ARB_RPC required for fork
[[ -z "${ARB_RPC:-}" ]] && die "ARB_RPC not set in .env — needed for Arbitrum Sepolia fork"

anvil \
  --fork-url "$ARB_RPC" \
  --chain-id $CHAIN_ID \
  --accounts 10 \
  --balance 10000 \
  --port 8545 \
  --silent &
echo $! > "$ANVIL_PID_FILE"
sleep 2

cast block-number --rpc-url "$RPC" > /dev/null 2>&1 || die "Anvil failed to start"
success "Anvil running (pid $(cat $ANVIL_PID_FILE))"

# Fund deployer if not using anvil default key
if [[ "${DEPLOY_ADDR,,}" != "${ANVIL_ADDR,,}" ]]; then
  info "Funding deployer $DEPLOY_ADDR with 100 ETH..."
  $CAST_SEND "$DEPLOY_ADDR" --value 100ether --private-key "$ANVIL_PK" > /dev/null
  success "Funded"
fi

# =============================================================================
section "STEP 1 — Deploy Mock Tokens"
# =============================================================================

info "Deploying MockUSDC + MockUSDT..."
$FORGE script/00_DeployMockTokens.s.sol:DeployMockTokens \
  --private-key "$DEPLOY_PK" > /tmp/ps_00.txt 2>&1 \
  || { cat /tmp/ps_00.txt; die "Step 1 failed"; }
sleep 1

TOKEN0=$(broadcast_addr "00_DeployMockTokens.s.sol" 0)
TOKEN1=$(broadcast_addr "00_DeployMockTokens.s.sol" 1)
[[ -z "$TOKEN0" ]] && die "TOKEN0 not found in broadcast"
[[ -z "$TOKEN1" ]] && die "TOKEN1 not found in broadcast"

setenv "TOKEN0_ADDRESS" "$TOKEN0"
setenv "TOKEN1_ADDRESS" "$TOKEN1"
success "TOKEN0 (USDC): $TOKEN0"
success "TOKEN1 (USDT): $TOKEN1"

# =============================================================================
section "STEP 2 — Deploy Hook"
# =============================================================================

info "Mining hook address and deploying..."
TOKEN0_ADDRESS=$TOKEN0 TOKEN1_ADDRESS=$TOKEN1 \
  $FORGE script/01_DeployHook.s.sol:DeployHookScript \
  --private-key "$DEPLOY_PK" > /tmp/ps_01.txt 2>&1 \
  || { cat /tmp/ps_01.txt; die "Step 2 failed"; }
sleep 1

HOOK=$(broadcast_addr "01_DeployHook.s.sol" 0)
[[ -z "$HOOK" ]] && die "HOOK not found in broadcast"

setenv "HOOK_ADDRESS" "$HOOK"
success "Hook: $HOOK"

# =============================================================================
section "STEP 3 — Create Pool + Concentrated Liquidity [-60, +60]"
# =============================================================================

info "Creating pool at \$1.00 + minting $((AMT_CONCENTRATED/1000000))k concentrated..."
TOKEN0_ADDRESS=$TOKEN0 TOKEN1_ADDRESS=$TOKEN1 HOOK_ADDRESS=$HOOK \
  AMOUNT0=$AMT_CONCENTRATED AMOUNT1=$AMT_CONCENTRATED \
  $FORGE script/02_CreatePoolAndAddLiquidity.s.sol:CreatePoolAndAddLiquidityScript --skip-simulation \
  --private-key "$DEPLOY_PK" > /tmp/ps_02.txt 2>&1 \
  || { cat /tmp/ps_02.txt; die "Step 3 failed"; }
sleep 1

POOL_ID=$(cast keccak $(cast abi-encode \
  "f(address,address,uint24,int24,address)" \
  $TOKEN0 $TOKEN1 8388608 60 $HOOK))

# On Arbitrum Sepolia fork, deployArtifacts() uses canonical V4 addresses automatically
# Extract them from the forge trace output of script 02
POOL_MANAGER=$(grep -oE '"V4PoolManager": "0x[0-9a-fA-F]{40}"' /tmp/ps_02.txt | grep -oE '0x[0-9a-fA-F]{40}' | head -1 || echo "")
POS_MANAGER=$(grep  -oE '"V4PositionManager": "0x[0-9a-fA-F]{40}"' /tmp/ps_02.txt | grep -oE '0x[0-9a-fA-F]{40}' | head -1 || echo "")
PERMIT2_ADDR=$(grep -oE '"Permit2": "0x[0-9a-fA-F]{40}"' /tmp/ps_02.txt | grep -oE '0x[0-9a-fA-F]{40}' | head -1 || echo "")
SWAP_ROUTER=$(grep  -oE '"V4SwapRouter": "0x[0-9a-fA-F]{40}"' /tmp/ps_02.txt | grep -oE '0x[0-9a-fA-F]{40}' | head -1 || echo "")

# Fallback: use known Arbitrum Sepolia canonical addresses
POOL_MANAGER="${POOL_MANAGER:-0xFB3e0C6F74eB1a21CC1Da29aeC80D2Dfe6C9a317}"
POS_MANAGER="${POS_MANAGER:-0xAc631556d3d4019C95769033B5E719dD77124BAc}"
PERMIT2_ADDR="${PERMIT2_ADDR:-0x000000000022D473030F116dDEE9F6B43aC78BA3}"
SWAP_ROUTER="${SWAP_ROUTER:-0xcD807e10A7A794389d6A7d83C739Af874882f7F9}"

setenv "POOL_ID"             "$POOL_ID"
setenv "POOL_MANAGER"        "${POOL_MANAGER:-}"
setenv "POSITION_MANAGER"    "${POS_MANAGER:-}"
setenv "PERMIT2"             "${PERMIT2_ADDR:-}"
setenv "SWAP_ROUTER_ADDRESS" "${SWAP_ROUTER:-}"

success "Pool ID: $POOL_ID"
[[ -n "$POOL_MANAGER" ]] && success "PoolManager:     $POOL_MANAGER"  || warn "PoolManager not captured from trace (vault will auto-configure)"
[[ -n "$POS_MANAGER" ]]  && success "PositionManager: $POS_MANAGER"   || true
[[ -n "$PERMIT2_ADDR" ]] && success "Permit2:         $PERMIT2_ADDR"  || true
[[ -n "$SWAP_ROUTER" ]]  && success "SwapRouter:      $SWAP_ROUTER"   || warn "SwapRouter not captured — swap steps will be skipped"

# =============================================================================
section "STEP 4 — Deploy Vault"
# =============================================================================

info "Deploying PegSentinelVault..."
TOKEN0_ADDRESS=$TOKEN0 TOKEN1_ADDRESS=$TOKEN1 \
  OWNER=$DEPLOY_ADDR HOOK_ADDRESS=$HOOK \
  POOL_FEE=8388608 TICK_SPACING=60 \
  POOL_MANAGER="${POOL_MANAGER:-}" \
  POSITION_MANAGER="${POS_MANAGER:-}" \
  PERMIT2="${PERMIT2_ADDR:-}" \
  $FORGE script/03_DeployVault.s.sol:DeployVault \
  --private-key "$DEPLOY_PK" > /tmp/ps_03.txt 2>&1 \
  || { cat /tmp/ps_03.txt; die "Step 4 failed"; }
sleep 1

VAULT=$(broadcast_addr "03_DeployVault.s.sol" 0)
[[ -z "$VAULT" ]] && die "VAULT not found in broadcast"

setenv "VAULT_ADDRESS" "$VAULT"
success "Vault: $VAULT"

info "Setting keeper = deployer..."
$CAST_SEND $VAULT "setKeeper(address)" $DEPLOY_ADDR \
  --private-key "$DEPLOY_PK" > /dev/null
success "Keeper set"

# =============================================================================
section "STEP 5 — Fund Vault"
# =============================================================================

info "Funding vault with $((AMT_VAULT_FUND/1000000))k USDC + USDT..."
$CAST_SEND $TOKEN0 "approve(address,uint256)" $VAULT $AMT_VAULT_FUND \
  --private-key "$DEPLOY_PK" > /dev/null
$CAST_SEND $TOKEN1 "approve(address,uint256)" $VAULT $AMT_VAULT_FUND \
  --private-key "$DEPLOY_PK" > /dev/null
$CAST_SEND $VAULT "fund(uint256,uint256)" $AMT_VAULT_FUND $AMT_VAULT_FUND \
  --private-key "$DEPLOY_PK" > /dev/null
success "Vault funded"

# =============================================================================
section "STEP 6 — Mint LP Position to Vault [-60, +60]"
# =============================================================================

info "Minting concentrated LP to vault..."
TOKEN0_ADDRESS=$TOKEN0 TOKEN1_ADDRESS=$TOKEN1 HOOK_ADDRESS=$HOOK \
  VAULT_ADDRESS=$VAULT \
  AMOUNT0=$AMT_CONCENTRATED AMOUNT1=$AMT_CONCENTRATED \
  $FORGE script/05_MintPositionToVault.s.sol:MintPositionToVault --skip-simulation \
  --private-key "$DEPLOY_PK" > /tmp/ps_05.txt 2>&1 \
  || { cat /tmp/ps_05.txt; die "Step 6 failed"; }
sleep 1

LP_TOKEN_ID=$(grep -oE 'tokenId.*[0-9]+' /tmp/ps_05.txt | grep -oE '[0-9]+' | tail -1 || echo "")
setenv "LP_TOKEN_ID" "${LP_TOKEN_ID:-unknown}"
success "LP position tokenId: ${LP_TOKEN_ID:-unknown}"

# =============================================================================
section "STEP 7 — Mint Full-Range Backstop [-887220, +887220]"
# =============================================================================

info "Minting $((AMT_BACKSTOP/1000000))k full-range backstop to EOA..."
TOKEN0_ADDRESS=$TOKEN0 TOKEN1_ADDRESS=$TOKEN1 HOOK_ADDRESS=$HOOK \
  AMOUNTBS0=$AMT_BACKSTOP AMOUNTBS1=$AMT_BACKSTOP \
  $FORGE script/06_MintPositionToEOA.s.sol:MintFullRangePosition --skip-simulation \
  --private-key "$DEPLOY_PK" > /tmp/ps_06.txt 2>&1 \
  || { cat /tmp/ps_06.txt; die "Step 7 failed"; }
sleep 1

success "Backstop minted"

# =============================================================================
section "STEP 8 — Verify Initial State"
# =============================================================================

TICK=$(cast call $VAULT "getCurrentTick()(int24)" --rpc-url "$RPC")
BALS=$(cast call $VAULT "balances()(uint256,uint256)" --rpc-url "$RPC")
REGIME=$(cast call $VAULT "activeRegime()(uint8)" --rpc-url "$RPC")

info "Initial state — Tick: $TICK | Regime: $REGIME | Balances: $BALS"
[[ "$REGIME" == "0" ]] && success "Regime = Normal ✓" || warn "Unexpected regime: $REGIME"

# =============================================================================
section "STEP 9 — Stress Swap"
# =============================================================================

if [[ -z "${SWAP_ROUTER:-}" ]]; then
  warn "SwapRouter not captured — skipping swap/rebalance test"
  warn "Check /tmp/ps_02.txt for 'V4SwapRouter' label"
else
  info "Swapping $((AMT_SWAP_STRESS/1000000))k USDC → USDT (pushing price down)..."
  $CAST_SEND $TOKEN0 "approve(address,uint256)" $SWAP_ROUTER \
    $(python3 -c "print($AMT_SWAP_STRESS * 3)") \
    --private-key "$DEPLOY_PK" > /dev/null

  AMOUNT_IN=$AMT_SWAP_STRESS ZERO_FOR_ONE=true \
  TOKEN0_ADDRESS=$TOKEN0 TOKEN1_ADDRESS=$TOKEN1 HOOK_ADDRESS=$HOOK \
    $FORGE script/Swap.s.sol:SwapScript --skip-simulation \
    --private-key "$DEPLOY_PK" > /tmp/ps_swap1.txt 2>&1 \
    || { warn "Swap failed:"; cat /tmp/ps_swap1.txt; }
  sleep 1

  TICK_AFTER=$(cast call $VAULT "getCurrentTick()(int24)" --rpc-url "$RPC")
  info "Tick after swap: $TICK_AFTER"

  # ── Step 10: Deploy buffer ─────────────────────────────────────────────────
  section "STEP 10 — autoRebalance (Normal → Defend)"

  NEEDED=$(cast call $VAULT "needsRebalance()(bool,uint8,uint8,int24)" \
    --rpc-url "$RPC" | head -1 | tr -d '[:space:]')
  info "needsRebalance: $NEEDED"

  # ── Pre-rebalance diagnostics ────────────────────────────────────────────
  info "--- Pre-rebalance diagnostics ---"

  T0=$(cast call $VAULT "token0()(address)" --rpc-url "$RPC")
  T1=$(cast call $VAULT "token1()(address)" --rpc-url "$RPC")
  info "  vault.token0():  $T0"
  info "  TOKEN0 env:      $TOKEN0"
  [[ "${T0,,}" == "${TOKEN0,,}" ]] && success "  token0 match ✓" || warn "  token0 MISMATCH ✗"

  info "  vault.token1():  $T1"
  info "  TOKEN1 env:      $TOKEN1"
  [[ "${T1,,}" == "${TOKEN1,,}" ]] && success "  token1 match ✓" || warn "  token1 MISMATCH ✗"

  VAULT_BALS=$(cast call $VAULT "balances()(uint256,uint256)" --rpc-url "$RPC")
  BAL0=$(echo "$VAULT_BALS" | head -1 | tr -d '[:space:]')
  BAL1=$(echo "$VAULT_BALS" | tail -1 | tr -d '[:space:]')
  info "  vault token0 bal: $BAL0 ($(python3 -c "print(f'{int($BAL0)/1e6:.2f}')" 2>/dev/null || echo "?") USDC)"
  info "  vault token1 bal: $BAL1 ($(python3 -c "print(f'{int($BAL1)/1e6:.2f}')" 2>/dev/null || echo "?") USDT)"
  [[ "$BAL1" == "0" ]] && warn "  ⚠️  USDT balance is 0 — buffer deploy will fail" || success "  USDT available ✓"

  POOL_ID_ONCHAIN=$(cast call $VAULT "getPoolId()(bytes32)" --rpc-url "$RPC" 2>/dev/null || echo "n/a")
  info "  vault poolId:    $POOL_ID_ONCHAIN"
  info "  computed poolId: $POOL_ID"
  [[ "${POOL_ID_ONCHAIN,,}" == "${POOL_ID,,}" ]] && success "  pool ID match ✓" || warn "  pool ID MISMATCH ✗"

  BUF_RANGE=$(cast call $VAULT "bufferRange()(int24,int24)" --rpc-url "$RPC")
  DEFEND_THRESH=$(cast call $VAULT "defendThreshold()(int24)" --rpc-url "$RPC")
  RECOVER_THRESH=$(cast call $VAULT "recoverThreshold()(int24)" --rpc-url "$RPC")
  info "  bufferRange:     $BUF_RANGE"
  info "  defendThreshold: $DEFEND_THRESH"
  info "  recoverThreshold:$RECOVER_THRESH"
  info "  currentTick:     $TICK_AFTER"

  # Verify tick is actually below defend threshold
  DEFEND_NUM=$(echo "$DEFEND_THRESH" | tr -d '[:space:]')
  TICK_NUM=$(echo "$TICK_AFTER" | tr -d '[:space:]')
  if python3 -c "exit(0 if int('$TICK_NUM') <= int('$DEFEND_NUM') else 1)" 2>/dev/null; then
    success "  tick ($TICK_NUM) <= defendThreshold ($DEFEND_NUM) ✓"
  else
    warn "  tick ($TICK_NUM) > defendThreshold ($DEFEND_NUM) — rebalance should NOT be needed"
  fi
  # Check autoRebalance preconditions from the contract
  KEEPER=$(cast call $VAULT "keeper()(address)" --rpc-url "$RPC")
  info "  keeper:          $KEEPER"
  info "  deployer:        $DEPLOY_ADDR"
  [[ "${KEEPER,,}" == "${DEPLOY_ADDR,,}" ]] && success "  keeper match ✓" || warn "  keeper MISMATCH ✗ — autoRebalance will revert NotKeeperOrOwner"

  POS_MGR=$(cast call $VAULT "positionManager()(address)" --rpc-url "$RPC")
  info "  positionManager: $POS_MGR"
  [[ "$POS_MGR" == "0x0000000000000000000000000000000000000000" ]]     && warn "  positionManager is ZERO — autoRebalance will revert PositionManagerNotSet"     || success "  positionManager set ✓"

  PAUSED=$(cast call $VAULT "paused()(bool)" --rpc-url "$RPC")
  info "  paused:          $PAUSED"
  [[ "$PAUSED" == "true" ]] && warn "  vault is PAUSED — autoRebalance will revert" || success "  not paused ✓"

  COOLDOWN=$(cast call $VAULT "rebalanceCooldown()(uint256)" --rpc-url "$RPC")
  LAST_REBAL=$(cast call $VAULT "lastRebalanceAt()(uint256)" --rpc-url "$RPC")
  NOW=$(cast block-number --rpc-url "$RPC")
  info "  cooldown:        $COOLDOWN sec | lastRebalanceAt: $LAST_REBAL | blockNumber: $NOW"

  # Check bytecode — verify fix is deployed by looking for the fixed selector pattern
  BYTECODE=$(cast code $VAULT --rpc-url "$RPC" 2>/dev/null | wc -c)
  info "  vault bytecode:  ${BYTECODE} chars"

  info "--- End diagnostics ---"
  # ─────────────────────────────────────────────────────────────────────────

  if [[ "$NEEDED" == "true" ]]; then
    info "Calling autoRebalance()..."
    $CAST_SEND $VAULT "autoRebalance()" \
      --private-key "$DEPLOY_PK" > /tmp/ps_rebal1.txt 2>&1 \
      || { cat /tmp/ps_rebal1.txt; warn "autoRebalance failed — see above"; }

    REGIME_AFTER=$(cast call $VAULT "activeRegime()(uint8)" --rpc-url "$RPC")
    BUF_LIQ=$(cast call $VAULT "getBufferLiquidity()(uint128)" --rpc-url "$RPC")
    BALS_AFTER=$(cast call $VAULT "balances()(uint256,uint256)" --rpc-url "$RPC")
    [[ "$REGIME_AFTER" == "1" ]] \
      && success "✅ Regime → Defend | Buffer liquidity: $BUF_LIQ" \
      || warn "Regime still $REGIME_AFTER (tick $TICK_AFTER may be above -50 threshold)"
    info "  Vault balances after deploy: $BALS_AFTER"
  else
    warn "needsRebalance=false — try increasing AMT_SWAP_STRESS"
  fi

  # ── Step 11: Remove buffer ─────────────────────────────────────────────────
  section "STEP 11 — Recovery Swap + autoRebalance (Defend → Normal)"

  info "Swapping $((AMT_SWAP_RECOVERY/1000000))k USDT → USDC (restoring peg)..."
  $CAST_SEND $TOKEN1 "approve(address,uint256)" $SWAP_ROUTER \
    $(python3 -c "print($AMT_SWAP_RECOVERY * 3)") \
    --private-key "$DEPLOY_PK" > /dev/null

  AMOUNT_IN=$AMT_SWAP_RECOVERY ZERO_FOR_ONE=false \
  TOKEN0_ADDRESS=$TOKEN0 TOKEN1_ADDRESS=$TOKEN1 HOOK_ADDRESS=$HOOK \
    $FORGE script/Swap.s.sol:SwapScript --skip-simulation \
    --private-key "$DEPLOY_PK" > /tmp/ps_swap2.txt 2>&1 \
    || { warn "Recovery swap failed:"; cat /tmp/ps_swap2.txt; }
  sleep 1

  TICK_RECOVER=$(cast call $VAULT "getCurrentTick()(int24)" --rpc-url "$RPC")
  info "Tick after recovery: $TICK_RECOVER"

  NEEDED2=$(cast call $VAULT "needsRebalance()(bool,uint8,uint8,int24)" \
    --rpc-url "$RPC" | head -1 | tr -d '[:space:]')

  if [[ "$NEEDED2" == "true" ]]; then
    info "Waiting 65s for cooldown to expire..."
    sleep 65
    info "Calling autoRebalance() to remove buffer..."
    $CAST_SEND $VAULT "autoRebalance()" \
      --private-key "$DEPLOY_PK" > /tmp/ps_rebal2.txt 2>&1 \
      || { cat /tmp/ps_rebal2.txt; warn "autoRebalance (remove) failed"; }

    REGIME_FINAL=$(cast call $VAULT "activeRegime()(uint8)" --rpc-url "$RPC")
    BALS_FINAL=$(cast call $VAULT "balances()(uint256,uint256)" --rpc-url "$RPC")
    [[ "$REGIME_FINAL" == "0" ]] \
      && success "✅ Regime → Normal | Final balances: $BALS_FINAL" \
      || warn "Regime still Defend — tick $TICK_RECOVER may be in hysteresis band [-50,-30]"
  else
    warn "needsRebalance=false — tick $TICK_RECOVER in hysteresis band, no action needed"
  fi
fi

# =============================================================================
section "SUMMARY"
# =============================================================================

echo ""
echo "  TOKEN0 (USDC):  $TOKEN0"
echo "  TOKEN1 (USDT):  $TOKEN1"
echo "  HOOK:           $HOOK"
echo "  VAULT:          $VAULT"
echo "  POOL_ID:        $POOL_ID"
echo "  LP_TOKEN_ID:    ${LP_TOKEN_ID:-unknown}"
echo ""
success "Env saved to $ENV_OUT"
echo "  set -a; source $ENV_OUT; set +a"
echo ""
success "Done 🎉"
